name: catalinadev
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+11

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line
  package_info_plus: ^1.4.2
  provider: ^6.0.3
  flutter_phoenix: ^1.0.0
  http: ^0.13.4
  localstorage: ^4.0.0+1
  shared_preferences: ^2.0.15
  flutter_font_icons: ^2.2.5
  flutter_spinkit: ^5.1.0
  image_picker: ^0.8.5+3
  uiblock: ^2.0.2
  path_provider: ^2.0.11
  animated_bottom_navigation_bar: ^1.0.0
  smooth_page_indicator: ^1.0.0+2
  carousel_slider: ^4.1.1
  flutter_countdown_timer: ^4.1.0
  cached_network_image: ^3.2.1
  shimmer: ^2.0.0
  introduction_screen: ^3.0.2
  auto_size_text: ^3.0.0
  webview_flutter: ^3.0.4
  flutter_rating_bar: ^4.0.1
  intl: ^0.17.0
  html_unescape: ^2.0.0
  money2: ^3.1.3
  url_launcher: ^6.1.4
  launch_review: ^3.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_html: ^2.2.1
  flutter_multi_formatter: ^2.5.7
  html_editor_enhanced: ^2.5.0
  currency_text_input_formatter: ^2.1.7
  multi_select_flutter:
    git:
      url: https://github.com/kabagouda/multi_select_flutter.git
      ref: patch-1 # branch name
  firebase_messaging: ^11.4.2
  uni_links: ^0.5.1
  flutter_local_notifications: ^9.6.1
  marquee: ^2.2.3
  country_pickers: ^2.0.0
  change_app_package_name: ^1.1.0
  modal_bottom_sheet: ^2.1.0
  upgrader: ^4.4.0
  pin_code_fields: ^7.4.0
  flutter_math_fork: ^0.6.3+1
  slugify: ^2.0.0
  firebase_core: ^1.18.0
  firebase_auth: ^3.3.20
  rxdart: ^0.27.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  country_code_picker: ^2.0.2
  share_plus: ^4.0.9
  pinput: ^2.2.11

  # Comment AdMob pacakge if not want to use it
  google_mobile_ads: ^1.3.0


dependency_overrides:
  flutter_svg: ^1.1.6
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logoBrand/
    - assets/images/home/
    - assets/images/detail/
    - assets/images/myOrder/
    - assets/images/account/
    - assets/images/cart/
    - assets/images/chat/
    - assets/images/store/
    - i18n/id.json
    - i18n/en.json
    - i18n/pt.json
    - i18n/km.json
    - i18n/ja.json
    - i18n/vi.json
    - i18n/es.json
    - i18n/fr.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
    - family: Brandon
      fonts:
        - asset: assets/fonts/Brandon_reg.otf
        - asset: assets/fonts/Brandon_med.otf
          weight: 600
        - asset: assets/fonts/Brandon_bld.otf
          weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
